### ISSUE TITLE
References to deleted images throw unwanted exception in article content

### ISSUE THREAD

**Issue by psiemens** [ubyssey/dispatch#715]
From Stackdriver production logs:

```
Internal Server Error: /api/articles/51182/rendered/ (/base/data/home/apps/s~ubyssey-prd/20170928t013905.404414880895705010/lib/django/core/handlers/exception.py:135)
Traceback (most recent call last):
  File "/base/data/home/apps/s~ubyssey-prd/20170928t013905.404414880895705010/lib/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/base/data/home/apps/s~ubyssey-prd/20170928t013905.404414880895705010/lib/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/base/data/home/apps/s~ubyssey-prd/20170928t013905.404414880895705010/lib/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/base/data/home/apps/s~ubyssey-prd/20170928t013905.404414880895705010/lib/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/base/data/home/apps/s~ubyssey-prd/20170928t013905.404414880895705010/ubyssey/views/main.py", line 114, in article_ajax
    'html': loader.render_to_string(article.get_template_path(), context)
  File "/base/data/home/apps/s~ubyssey-prd/20170928t013905.404414880895705010/lib/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/base/data/home/apps/s~ubyssey-prd/20170928t013905.404414880895705010/lib/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/base/data/home/apps/s~ubyssey-prd/20170928t013905.404414880895705010/lib/django/template/base.py", line 207, in render
    return self._render(context)
  File "/base/data/home/apps/s~ubyssey-prd/20170928t013905.404414880895705010/lib/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/base/data/home/apps/s~ubyssey-prd/20170928t013905.404414880895705010/lib/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/base/data/home/apps/s~ubyssey-prd/20170928t013905.404414880895705010/lib/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/base/data/home/apps/s~ubyssey-prd/20170928t013905.404414880895705010/lib/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/base/data/home/apps/s~ubyssey-prd/20170928t013905.404414880895705010/lib/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/base/data/home/apps/s~ubyssey-prd/20170928t013905.404414880895705010/lib/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/base/data/home/apps/s~ubyssey-prd/20170928t013905.404414880895705010/lib/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/base/data/home/apps/s~ubyssey-prd/20170928t013905.404414880895705010/lib/django/template/loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "/base/data/home/apps/s~ubyssey-prd/20170928t013905.404414880895705010/lib/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/base/data/home/apps/s~ubyssey-prd/20170928t013905.404414880895705010/lib/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/base/data/home/apps/s~ubyssey-prd/20170928t013905.404414880895705010/lib/django/template/base.py", line 1040, in render
    output = self.filter_expression.resolve(context)
  File "/base/data/home/apps/s~ubyssey-prd/20170928t013905.404414880895705010/lib/django/template/base.py", line 708, in resolve
    obj = self.var.resolve(context)
  File "/base/data/home/apps/s~ubyssey-prd/20170928t013905.404414880895705010/lib/django/template/base.py", line 849, in resolve
    value = self._resolve_lookup(context)
  File "/base/data/home/apps/s~ubyssey-prd/20170928t013905.404414880895705010/lib/django/template/base.py", line 890, in _resolve_lookup
    current = getattr(current, bit)
  File "/base/data/home/apps/s~ubyssey-prd/20170928t013905.404414880895705010/lib/dispatch/modules/content/models.py", line 112, in html
    return content_to_html(self.content)
  File "/base/data/home/apps/s~ubyssey-prd/20170928t013905.404414880895705010/lib/dispatch/modules/content/render.py", line 16, in content_to_html
    return mark_safe(reduce(render_node, content, ''))
  File "/base/data/home/apps/s~ubyssey-prd/20170928t013905.404414880895705010/lib/dispatch/modules/content/render.py", line 14, in render_node
    return html + embedlib.render(node['type'], node['data'])
  File "/base/data/home/apps/s~ubyssey-prd/20170928t013905.404414880895705010/lib/dispatch/modules/content/embeds.py", line 25, in render
    return self.get_controller(type).render(data)
  File "/base/data/home/apps/s~ubyssey-prd/20170928t013905.404414880895705010/lib/dispatch/modules/content/embeds.py", line 50, in render
    return template.render(self.prepare_data(data))
  File "/base/data/home/apps/s~ubyssey-prd/20170928t013905.404414880895705010/lib/dispatch/modules/content/embeds.py", line 112, in prepare_data
    image = self.get_image(id)
  File "/base/data/home/apps/s~ubyssey-prd/20170928t013905.404414880895705010/lib/dispatch/modules/content/embeds.py", line 106, in get_image
    raise EmbedException('Image with id %d does not exist' % id)
EmbedException: Image with id 25538 does not exist
```

```
Internal Server Error: /api/articles/ (/base/data/home/apps/s~ubyssey-prd/20170928t013905.404414880895705010/lib/django/core/handlers/exception.py:135)
Traceback (most recent call last):
  File "/base/data/home/apps/s~ubyssey-prd/20170928t013905.404414880895705010/lib/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/base/data/home/apps/s~ubyssey-prd/20170928t013905.404414880895705010/lib/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/base/data/home/apps/s~ubyssey-prd/20170928t013905.404414880895705010/lib/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/base/data/home/apps/s~ubyssey-prd/20170928t013905.404414880895705010/lib/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/base/data/home/apps/s~ubyssey-prd/20170928t013905.404414880895705010/lib/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/base/data/home/apps/s~ubyssey-prd/20170928t013905.404414880895705010/lib/rest_framework/viewsets.py", line 83, in view
    return self.dispatch(request, *args, **kwargs)
  File "/base/data/home/apps/s~ubyssey-prd/20170928t013905.404414880895705010/lib/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/base/data/home/apps/s~ubyssey-prd/20170928t013905.404414880895705010/lib/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/base/data/home/apps/s~ubyssey-prd/20170928t013905.404414880895705010/lib/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/base/data/home/apps/s~ubyssey-prd/20170928t013905.404414880895705010/lib/rest_framework/mixins.py", line 45, in list
    return self.get_paginated_response(serializer.data)
  File "/base/data/home/apps/s~ubyssey-prd/20170928t013905.404414880895705010/lib/rest_framework/serializers.py", line 729, in data
    ret = super(ListSerializer, self).data
  File "/base/data/home/apps/s~ubyssey-prd/20170928t013905.404414880895705010/lib/rest_framework/serializers.py", line 262, in data
    self._data = self.to_representation(self.instance)
  File "/base/data/home/apps/s~ubyssey-prd/20170928t013905.404414880895705010/lib/rest_framework/serializers.py", line 647, in to_representation
    self.child.to_representation(item) for item in iterable
  File "/base/data/home/apps/s~ubyssey-prd/20170928t013905.404414880895705010/lib/rest_framework/serializers.py", line 500, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/base/data/home/apps/s~ubyssey-prd/20170928t013905.404414880895705010/lib/dispatch/api/serializers.py", line 267, in to_representation
    return self.insert_data(content)
  File "/base/data/home/apps/s~ubyssey-prd/20170928t013905.404414880895705010/lib/dispatch/api/serializers.py", line 297, in insert_data
    block['data']['image'] = ImageSerializer(self.images[block['data']['image_id']]).data
KeyError: 25538
```

**Proposed fix:** image attachments with references to deleted/nonexistent images should return `None` for the image field.

**Comment by psiemens** [comment]
Implemented in #716
